### ISSUE TITLE
Building error

### ISSUE THREAD

**Issue by Wzedlare** [SlimRoms/frameworks_opt_slim#3]
These errors pop up while building slim n7.1 for my device
![cats](https://cloud.githubusercontent.com/assets/20111328/20065306/afcdecc6-a51e-11e6-8a0b-8fbbe4557aab.jpg)

**Comment by YumeMichi** [comment]
7.1 is WIP
https://review.slimroms.org/22352
https://review.slimroms.org/22353

**Comment by Wzedlare** [comment]
I will try again after it goes out from WIP status
